const express = require('express')

const swaggerUi = require('swagger-ui-express')
const swaggerFile = require('./swagger-output.json')

const app = express()
const env = require("dotenv")
env.config({path:"./config/.env"})
const cors =require("cors")
const db = require("./config/db")
const addToCart = require("./routes/addToCart_routes")
const addToHotelInformation = require("./routes/AddtoHotelInformation_routes")
const admin = require("./routes/admin_routes")
const adminLogin =require("./routes/adminLogin_routes")
const category = require("./routes/category_routes")
const contact = require("./routes/contactus_routes") 
const CustomerReview = require("./routes/customerReview_routes")
const deliveryBoy =require("./routes/deliveryBoy_routes")
const enquiry = require("./routes/enquiry_routes")
const forgotPassword = require("./routes/forgotPassword_routes")
const forgotPasswordforHotelOwner = require("./routes/forgotPasswordforHotelOwner")
const HotelLogin = require("./routes/hotelLogin_routes")
const HotelOwner = require("./routes/HotelRegister_routes")
const HotelMenu = require("./routes/addtoMenuCard")
const order =require("./routes/order_routes")
const payment =require("./routes/payment_routes")
const plan =require("./routes/plan_routes")
const product = require("./routes/product_routes")
const resetPassword = require("./routes/resetPasswordHotelOwner")
const searchApi = require("./routes/searchapiforuser_routes")
const user = require("./routes/user_routes")
const userlogin = require("./routes/userlogin_routes")
db()
app.use(express.json())
app.use('/swagger-api-doc', swaggerUi.serve, swaggerUi.setup(swaggerFile))
app.use(express.static('public'));
app.use(cors())
app.use("/api/v1/cart",addToCart)
app.use("/api/v1",addToHotelInformation)
app.use("/api/v1",admin)
app.use("/api/v1",adminLogin)
app.use("/api/v1",category)
app.use("/api/v1",contact)
app.use("/api/v1",CustomerReview)
app.use("/api/v1",deliveryBoy)
app.use("/api/v1",enquiry)
app.use("/api/v1",forgotPassword)
app.use("/api/v1",forgotPasswordforHotelOwner)
app.use("/api/v1",HotelLogin)
app.use("/api/v1",HotelOwner)
app.use("/api/v1",HotelMenu)
app.use("/api/v1",order)
app.use("/api/v1",payment)
app.use("/api/v1",plan)
app.use("/api/v1",product)
app.use("/api/v1",resetPassword)
app.use("/api/v1",searchApi)
app.use("/api/v1/user",user)
app.use("/api/v1",userlogin)
app.listen(process.env.PORT, () => console.log(`http://192.168.43.220:${process.env.PORT ||5000}`))
require('./endpoint')(app)